apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-management
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/chesney/argocd-config-repo
    targetRevision: HEAD
    path: . # Path to values.yaml in the config repo
    chart: argo-cd
    helm:
      valueFiles:
        - values.yaml
  project: default
